JAPANESE = {}

--Translates for 3.81

JAPANESE["UPDATER_AVAILABLE"] =			"の更新が有ります"
JAPANESE["UPDATER_UPDATE"] =			"アプリケーションの更新をしますか"
JAPANESE["CHINESE_FONT_DOWNLOAD"] =		"中国語のフォントのダウンロード"
JAPANESE["MENU_TRANSLATE"] =			"Autopluginの翻訳"
JAPANESE["TRANSLATE_ENGLISH_TITLE"] =		"English: "
JAPANESE["TRANSLATE_CURRENT_TITLE"] =		"現在の翻訳: "
JAPANESE["TRANSLATE_YOUR_TITLE"] =		"修正後の翻訳: "
JAPANESE["MENU_TRANSLATE_DESC"] =		"あなたの地域の言語を翻訳する事でAutopluginを改善に協力して下さい"
JAPANESE["SAVE_TRANSLATIONS"] =			"言語内容を保存"
JAPANESE["EXIT_SAVE_TRANSLATIONS"] =		"翻訳内容が保存されませんでした。終了する前に保存しますか?"
JAPANESE["TRANSLATION_SAVED_1"] =		"翻訳ファイルを以下の場所に保存しました :"
JAPANESE["TRANSLATION_SAVED_2"] =		"このファイルをAutopluginのGitHubにアップロードして下さい"
JAPANESE["NOTHING_TO_TRANSLATE"] =		"ご関心をお寄せいただきありがとうございます。現在翻訳する箇所はありません"
JAPANESE["STRING_UNSAFE_MODE"] =		"このアプリの起動にはUNSAFE MODEを有効にする必要があります"
JAPANESE["STRING_PSVITA_RESTART"] =		"PS Vitaを再起動します"
JAPANESE["STRING_BACKUP_CONFIGS"] =		"Config_backups.txtの作成"
JAPANESE["STRING_MISSING_CONFIG"] =		"config.txtが存在しません"
JAPANESE["STRING_BACK"] =			"メニューに戻る"
JAPANESE["STRING_CLOSE"] =			"Autopluginの終了"
JAPANESE["STRING_INSTALLED"] =			"は導入されました"
JAPANESE["STRING_PLEASE_WAIT"] =		"暫らくお待ち下さい"
JAPANESE["RESTART_QUESTION"] =			"今直ぐ再起動しますか?"

--Options Menus
JAPANESE["MENU_TITLE"] =			"Autoplugin"
JAPANESE["MENU_PSVITA"] =			"Vita用プラグイン"
JAPANESE["MENU_PSP"] =				"PSP(Adrenaline)用プラグイン"
JAPANESE["MENU_EXTRAS"] =			"特別メニュー"
JAPANESE["MENU_EXIT"] =				"終了"

--Desc Options PSVITA
JAPANESE["INSTALL_PLUGINS_DESC"] =		"SCENE-PSVITA製の最も有用なプラグインを導入して下さい"
JAPANESE["UNINSTALL_PLUGINS_DESC"] =		"プラグインを簡単にそしてシンプルに削除する"
JAPANESE["INSTALL_SD2VITA_DESC"] =		"SD2VITAプラグインの導入(CelesteBlue氏作StorageMgr)"
JAPANESE["CONFIG_SD2VITA_DESC"] =		"SD2VITAプラグインの設定(CelesteBlue氏作StorageMgr)"
JAPANESE["CHECK_ONLINEP_DESC"] =		"新しく更新されたプラグインの有無を確認します"

JAPANESE["MENU_TITLE_PSVITA"] =			"PS Vitaのプラグイン"
JAPANESE["MENU_INSTALL_SD2VITA"] =		"SD2VITAプラグインの導入"
JAPANESE["MENU_CONFIGURE_SD2VITA"] =		"SD2VITAプラグインの設定"
JAPANESE["MENU_INSTALL_PLUGINS"] =		"プラグインの導入"
JAPANESE["MENU_UNINSTALL_PLUGINS"] =		"プラグインの削除"
JAPANESE["MENU_CHECK_ONLINEP"] =		"プラグインの更新の確認"

JAPANESE["MENU_TITLE_PSP"] =			"PSP(Adrenaline)のプラグイン"
JAPANESE["MENU_INSTALL_NPDRMFREE"] =		"qwikrazor87氏作npdrm freeプラグインの導入"
JAPANESE["MENU_INSTALL_REMASTERED_CTRLS"] =	"TheOfficialFloW氏作RemasteredControls pluginsプラグインの導入"
JAPANESE["MENU_INSTALL_PLUGINS_PSP"] =		"AdrenalineのPSPプラグイン"

JAPANESE["MENU_CONVERTBOOTSPLASH"] =		"Custom Boot Splashの設定"
JAPANESE["MENU_CUSTOMWARNING"] =		"Custom Warning Messageの設定"
JAPANESE["MENU_INSTALL_CONFIG"] =		"PKGJ v0.45以上向けのconfig.txtの導入"
JAPANESE["MENU_INSTALL_CONFIG_DESC"] =		"PKGJ向けのconfig.txtの導入(Wi-Fi必須)"
JAPANESE["MENU_INSTALLED_CONFIG"] =		"ux0:pkgi/config.txtに導入されました"

JAPANESE["MENU_CUSTOM_CONFIG_DESC"] =		"PKGJのconfig.txtでのオプションのカスタマイズを許可します"


JAPANESE["MENU_HENCORE2"] =			"TheOfficialFloW氏作H-Encore Version2を導入"
JAPANESE["MENU_HENCORE2_DESC"] =		"TheOfficialFloW氏作H-Encore Version2へ更新(注意:H-Encoreが既に導入されている必要があります)"
JAPANESE["MENU_HENCORE2_ASK"] =			"H-Encore Version2は以下の場所に導入されます 場所:"
JAPANESE["MENU_INSTALLED_HENCORE2"] =		"H-Encore Version2は以下の場所に導入されました 場所:"
JAPANESE["MENU_NOT_INSTALLED_HENCORE2"] =	"H-Encore Version2は以下の場所に導入出来ませんでした 場所:"
JAPANESE["MENU_HENCORE2_PATCHED"] =		"H-Encore Version2を適用しました"
JAPANESE["MENU_HENCORE2_NOT_PATCHED"] =		"H-Encore Version2は適用出来ませんでした"
JAPANESE["MENU_HENCORE2_NOGAME"] =		"H-Encore Version2を更新するには、H-Encoreを導入しておく必要があります"

JAPANESE["MENU_QENCORE"] =			"Yoti氏作Q-Encoreの導入"
JAPANESE["MENU_QENCORE_DESC"] =			"Yoti氏作Quick H-encore launcher(警告:H-Encoreが導入されている必要があります)"
JAPANESE["MENU_QENCORE_ASK"] =			"Q-Encoreを導入する必要があります"
JAPANESE["MENU_INSTALLED_QENCORE"] =		"Q-Encoreは導入されました"
JAPANESE["MENU_NOT_INSTALLED_QENCORE"] =	"Q-Encoreは導入出来ませんでした"
JAPANESE["MENU_QENCORE_PATCHED"] =		"Q-Encoreのを適用しました"
JAPANESE["MENU_QENCORE_NOT_PATCHED"] =		"Q-Encoreの適用出来ませんでした"
JAPANESE["MENU_QENCORE_NOGAME"] =		"Q-Encoreを適用するにはH-Encoreを導入する必要があります"

--install sd2vita
JAPANESE["MENU_TITLE_SD2VITA"] =		"SD2VITA向けのStorage Managerプラグインを導入"
JAPANESE["SD2VITA_CONFIG_TITLE"] =		"SD2VITA向けのStorage Managerプラグインの設定"
JAPANESE["SD2VITA_CONFIG_DEVICE"] =		"端末"
JAPANESE["SD2VITA_CONFIG_MOUNT"] =		"マウントポイント"
JAPANESE["SD2VITA_CONFIG_CHANGE"] =		"マウントポイントの変更"
JAPANESE["SD2VITA_CONFIG_CANCEL"] =		"キャンセル"
JAPANESE["SD2VITA_CONFIG_SAVE"] =		"現在の設定を保存"
JAPANESE["SD2VITA_1_WARNING"] =			"Storage Managerプラグインを導入するにはSD2VITAが必要です"
JAPANESE["SD2VITA_2_WARNING"] =			"ゲームカードが挿入されている場合、アプリを再起動する前にゲームカードを取り外して下さい"
JAPANESE["SD2VITA_3_WARNING"] =			"最重要:SD2VITAには幾つかのアプリケーションが導入されている必要があります"
JAPANESE["SD2VITA_4_WARNING"] =			"純正メモリーカードから必要なアプリをSDカードにコピーして下さい"
JAPANESE["SD2VITA_5_WARNING"] =			"例:H-Encore・Vitashell・ONEMenu・PKGJ・Adrenaline等"
JAPANESE["SD2VITA_GAMECARD_DETECTED"] =		"ゲームカードを検出しました"
JAPANESE["SD2VITA_GAMECARD_REMOVED"] =		"導入前に取り外して下さい"
JAPANESE["SD2VITA_INSTALL"] =			"導入の続行"
JAPANESE["SD2VITA_CANCEL"] =			"導入のキャンセル"
JAPANESE["SD2VITA_INVALID_CONFIG"] =		"設定が無効です\n\n全てのマウントポイントが唯一である事と、又noneに設定されている事を確認して下さい\nux0:が設定されます"
JAPANESE["SD2VITA_UPDATED_CONFIG"] =		"Storage Managerの設定が更新されました"
JAPANESE["MOUNT_NONE_FRIENDLY"] =		"マウント解除"
JAPANESE["MOUNT_UX0_FRIENDLY"] =		"LiveAreaアプリケーション"
JAPANESE["MOUNT_XMC0_FRIENDLY"] =		"未使用"
JAPANESE["MOUNT_IMC0_FRIENDLY"] =		"PS Vita 2000/PS TVの内部メモリー"
JAPANESE["MOUNT_UMA0_FRIENDLY"] =		"USBポート"
JAPANESE["MOUNT_GRW0_FRIENDLY"] =		"ゲームカードスロット"
JAPANESE["SD2VITA_MCD_FRIENDLY"] =		"純正メモリーカード"
JAPANESE["SD2VITA_INT_FRIENDLY"] =		"PS Vita 2000/PS TVの内部メモリー"
JAPANESE["SD2VITA_GCD_FRIENDLY"] =		"SD2VITA"
JAPANESE["SD2VITA_UMA_FRIENDLY"] =		"PS VITA 1000のUSB又はPSVSD"

--install plugins
JAPANESE["INSTALLP_LIST_PLUGINS"] =		"導入可能なプラグイン一覧:"
JAPANESE["INSTALLP_MARK"] =			"プラグインの選択/選択解除"
JAPANESE["INSTALLP_CONFIRM"] =			"プラグインの導入"
JAPANESE["INSTALLP_ALL"] =			"全てのプラグインの導入"
JAPANESE["INSTALLP_CLEAN"] =			"選択したプラグインの選択解除"
JAPANESE["INSTALLP_LR_SWAP"] =			"ux0:/ur0:の切り替え"
JAPANESE["INSTALLP_CUSTOM_PATH"] =		"任意の場所に導入"

JAPANESE["INSTALLP_VITABRIGHT_360"] =		"VitabrightはFW3.60とH-Encore FW3.68専用です"
JAPANESE["INSTALLP_CWARNING_360_365"] =		"Custom WarningはFW3.67とFW3.68では動作しません"
JAPANESE["INSTALLP_QUESTION_SHELLSECBAT"] =	"\nshellsecbatプラグインを検出しました\n\nshellsecbatプラグインを削除して、\nshellbatプラグインを導入しますか?"
JAPANESE["INSTALLP_QUESTION_SHELLBAT"] =	"\nshellbatプラグインを検出しました\n\nshellbatプラグインを削除して、\nshellsecbatプラグインを導入しますか?"

JAPANESE["INSTALLP_WARNING_REFOOD"] =		"ur0:/taiに導入されてプラグインが正常に動作する様になりました"
JAPANESE["INSTALLP_OSK_TITLE"] =		"Custom Warningのテキスト"
JAPANESE["INSTALLP_OSK_TEXT"] =			"テキストをここに入力"

--Uninstall plugins
JAPANESE["UNINSTALLP_TITLE"] =			"プラグインマネージャー"
JAPANESE["UNINSTALLP_NOCONFIG_FOUND"] =		"以下の場所にconfig.txtが存在しません: "
JAPANESE["UNINSTALLP_PLUGIN"] =			"プラグインを削除"
JAPANESE["UNINSTALLP_LEFTRIGHT_SECTION"] =	"←ボタン/→ボタン セクションで切り替え"

--config pkgj
JAPANESE["PKGJ_TITLE"] =			"PKGJコンフィグの設定"
JAPANESE["NO_CONFIG_PKGJ"] =			"config.txtが導入されていません"
JAPANESE["YES"] =				"YES"
JAPANESE["NO"] =				"NO"
JAPANESE["PKGJ_UPDATE_CONFIG"] =		"PKGJのコンフィグを更新"
JAPANESE["PKGJ_UPDATING"] =			"PKGJのコンフィグを更新中\n\n暫くお待ち下さい"

JAPANESE["PKGJ_TITLE_INSTALL_PBP"] =		"PSPゲームをEBOOTファイルとして導入"
JAPANESE["PKGJ_DESC_INSTALL_PBP"] =		"より速くゲーム(EBOOT.PBP)を導入する事が出来ます。qwikrazor87氏作のNpdrm_freeプラグインを導入する必要があります"
JAPANESE["PKGJ_TITLE_CHANGE_LOC"] =		"PSP/PSXのパーティションの切り替え"
JAPANESE["PKGJ_DESC_CHANGE_LOC"] =		"PSPとPSXゲームを別のパーティションに導入する"
JAPANESE["PKGJ_TITLE_ADD_PSM"] =		"PSMゲームの追加"
JAPANESE["PKGJ_DESC_ADD_PSM"] =			"NoPsmDrmプラグインの導入が必要です"

--npdrm free
JAPANESE["NPDRMFREE_TITLE"] =			"qwikrazor87氏作npdrm freeプラグインの導入"
JAPANESE["NPDRMFREE_INSTALLED"] =		"npdrm freeが導入されました"
JAPANESE["NPDRMFREE_VSH_UPDATED"] =		"vsh.txtを更新しました"
JAPANESE["NPDRMFREE_GAME_UPDATED"] =		"game.txtを更新しました"
JAPANESE["NPDRMFREE_INSTALL"] =			"npdrm freeプラグインの導入"
JAPANESE["NPDRMFREE_DESC"] =			"npdrm freeは有効な.rifライセンスやact.datを必要とせずに、公式のPS1/PSPコンテンツを実行する為のPSP/ePSPプラグイン"

--customWarning
JAPANESE["CUSTOMWARNING_MESSAGE"] =		"Custom Warningプラグインを有効にする事を忘れないで下さい"

--customsplash
JAPANESE["CUSTOMBOOTSPLASH__TITLE"] =		"Custom Boot Splash"
JAPANESE["CUSTOMBOOTSPLASH_CONVERT"] =		"画像の変換"
JAPANESE["CUSTOMBOOTSPLASH_IMPORT"] =		"ギャラリーから画像をインポートする(.png限定)"
JAPANESE["CUSTOMBOOTSPLASH__MESSAGE"] =		"Custom Boot Splashプラグインを有効にする事を忘れないで下さい"
JAPANESE["CUSTOMBOOTSPLASH_NOPNG_FOUND"] =	"ux0:CustomBootsplashが空です"
JAPANESE["CUSTOMBOOTSPLASH_NOPNG"] =		"拡張子: .png"

--pspctrls
JAPANESE["PSPCTRLS_TITLE"] =			"TheOfficialFloW氏作(Adrenaline向け)Remastered Controlsプラグインの導入"
JAPANESE["PSPCTRLS_GAME_UPDATED"] =		"game.txtを更新しました"
JAPANESE["PSPCTRLS_DESC"] =			"Adrenaline上のPSPゲームをPS Vitaのデュアルアナログスティックで操作可能にする"
JAPANESE["PSPCTRLS_DESC_ALL"] =			"デュアルアナログスティックの有効"
JAPANESE["PSPCTRLS_LR_SWAP"] =			"パーティションを切り替え"

--psp plugins
JAPANESE["PLUGINS_PSP_TITLE"] =			"AdrenalineのPSPプラグインの利用可能一覧"
JAPANESE["PLUGINS_DESC"] =			"AdrenalineのPSPプラグインを導入"

JAPANESE["CAMERA_PATCH_DESC"] =			"このプラグインはAdrenalineのPSPゲームにアナログスティックサポートを追加する事が出来ます"
JAPANESE["CXMB_DESC"] =				"CXMBにより、PSP/テーマでカスタムCTFテーマを使用出来ます"
JAPANESE["LANGSWAPPER_DESC"] =			"PSPのゲームに設定される言語に、ゲームのホームメニューとデータ保存のユーティリティを設定します"
JAPANESE["CATEGORYLITE_DESC"] =			"全ての公式ゲーム・エミュレータ・自作アプリ・ゲームを、ゲームディレクトリの下の独自のフォルダに整理します"
JAPANESE["KHBBS_UNDUB_DESC"] =			"キングダムハーツ:バース バイ スリープ/ファイナル ミックス(日本語音声)の為のUNDUBのバージョン"

--plugins online
JAPANESE["UPDATE_WIFI_LOW"] =			"Wi-Fiの信号が弱いです"
JAPANESE["UPDATE_WIFI_IS_ON"] =			"インターネット環境が必要です"
JAPANESE["UPDATE_CHECK_DB"] =			"データーベースの確認"
JAPANESE["UPDATE_PLUGIN"] =			"プラグインの更新"
JAPANESE["UPDATE_ERROR_DB"] =			"db.luaのダウンロードエラー"
JAPANESE["UPDATE_NO_NEWS"] =			"全てのプラグインが最新です"
JAPANESE["UPDATE_VITACHEAT_DB"] =		"VitaCheatのデーターベースを更新しますか?"
JAPANESE["UPDATE_VITACHEAT_DB_WRITE"] =		"ファイルは上書き保存されます"
JAPANESE["UPDATE_CHECK_VITACHEAT_DB"] =		"VitaCheatデータベースの確認"

--descriptions plugins
--KERNEL
JAPANESE["INSTALLP_DESC_NONPDRM"] =		"どのようなPS VitaコンテンツでもDRM保護をバイパスが出来ます"
JAPANESE["INSTALLP_DESC_MINIVITATV"] =		"PS Vitaで最大4人とローカルマルチプレイゲームをプレイする事が出来ます"
JAPANESE["INSTALLP_DESC_NOPSMDRM"] =		"どの様なPSMのゲームコンテンツでもDRM保護をバイパスが出来ます"
JAPANESE["INSTALLP_DESC_VITABRIGHT"] =		"このプラグインを使用すると、輝度設定がカスタムガンマテーブルを使用する為、最小値と最大値の幅が広がります"
JAPANESE["INSTALLP_DESC_NOAVLS"] =		"AVLS-ForcedプラグインはVitaのAVLS機能を永久に無効にします"
JAPANESE["INSTALLP_DESC_REPATCH"] =		"ux0:patchの様な暗号化されたゲームの改造を可能にし、FW3.60・FW3.65・HENでFW3.67以上のゲームの使用を可能にします"
JAPANESE["INSTALLP_DESC_LOLICON"] =		"PS VitaのCPUクロックをオーバークロックしたり、画面上にフレームレートを表示させる事が出来ます"
JAPANESE["INSTALLP_DESC_DS3VITA"] =		"DualShock3を使用してPS Vitaを操作が出来ます"
JAPANESE["INSTALLP_DESC_DS4VITA"] =		"DualShock4を使用してPS Vitaを操作が出来ます"
JAPANESE["INSTALLP_DESC_UDCDUVC"] =		"UVCデバイスを使用して、USB経由でディスプレイをコンピュータにストリーミングします"
JAPANESE["INSTALLP_DESC_VIIMOTE"] =		"WiiMoteを使用してPS Vitaを操作が出来ます"
JAPANESE["INSTALLP_DESC_KUIO"] =		"基本的なI/O操作の場合、ユーザーモジュールux0:dataにアクセス出来る様にします/n特定のプラグインが必要な場合があります"
JAPANESE["INSTALLP_DESC_ADRENALINE"] =		"ワンタッチでAdrenalineを動作させる事が出来ます"
JAPANESE["INSTALLP_DESC_DSMOTION"] = 		"PS TVのDualShockモーションコントロールのサポート"
JAPANESE["INSTALLP_DESC_USBMC"] = 		"USBストレージをVitaのメモリーカード(ux0)としてマウントする事が出来ます"
JAPANESE["INSTALLP_DESC_ANALOGSENHANCER"] =	"この小さなカーネルプラグインにより、ユーザーはPS Vitaのアナログスティックの操作精度を向上させる事が出来ます"
JAPANESE["INSTALLP_DESC_IOPLUS"] = 		"ユーザランドでより多くのIO操作を可能にするPS Vitaカーネルプラグインです/n元の機能を使用して、ユーザーアプリケーションとプラグインのIO許可を向上させます"
JAPANESE["INSTALLP_DESC_VITACHEAT"] =		"PS Vitaゲームでチートを使用する"
JAPANESE["INSTALLP_DESC_NOPSMWHITE"] =		"PSMゲームのPS TV向けホワイトリストを無効にする"
JAPANESE["INSTALLP_DESC_ANALOGSTICK"] =		"PS Vitaのアナログスティックを完全に無効化するプラグイン"
JAPANESE["INSTALLP_DESC_CIDSPOOF"] =		"PS VitaのなりすましCID(PSNからコンソールの禁止を解除する為に使用される可能性があります)"
JAPANESE["INSTALLP_DESC_MAKEPSM"] =		"PSM Developerアプリケーションへの変更"
JAPANESE["INSTALLP_DESC_REFOOD"] =		"復号化されていないプログラムを実行する為のPS Vitaプラグイン"
JAPANESE["INSTALLP_DESC_NOLED"] =		"noledはPS Vitaのホームボタンを無効にするため為のシンプルなプラグイン"
JAPANESE["INSTALLP_DESC_NOSLEEP"] =		"スリープタイマーを無効にするtaiHEN・EnsoのVita用のシンプルなプラグイン"

--Boot_config.txt
JAPANESE["INSTALLP_DESC_CUSTOMBOOTSPLASH"] =	"このプラグインは、起動時にPS Vita／PS TVにBoot Splashを表示させる事が出来ます(ENSO必須)"
JAPANESE["INSTALLP_DESC_CONVERTBOOTSPLASH"] =	"スプラッシュイメージをカスタムブートスプラッシュとして設定しますか?"
JAPANESE["INSTALLP_DESC_NOFINDSPLASH"] =	"選択した画像をux0:CustomBootsplash/に配置します\n(splash.pngに名前を変更して、960×544にリサイズ)"
JAPANESE["INSTALLP_DESC_SPLASHGH"] =		"画像サイズは｢960×544｣です"
JAPANESE["INSTALLP_DESC_BOOTSPLASHDONE"] =	"boot_splash.binが完了しました"

--MAIN
JAPANESE["INSTALLP_DESC_DENABLER"] =		"ブラウザでファイルをダウンロードする事が出来ます"
JAPANESE["INSTALLP_DESC_NOLOCKSCREEN"] =	"PS Vitaのロック画面を無効にします"
JAPANESE["INSTALLP_DESC_NOTROPHYMSG"] =		"セーブデータが別のアカウントにリンクされているアプリケーションを起動すると、トロフィーヒントメッセージが無効になります。アカウントを常に切り替える場合に便利です"
JAPANESE["INSTALLP_DESC_CUSTOMWARNING"] =	"Ensoで起動する時に公式警告メッセージの代わりにカスタムメッセージを設定する事が出来ます"
JAPANESE["INSTALLP_DESC_SHELLBAT"] =		"ステータスバーのバッテリーのパーセントを表示します"
JAPANESE["INSTALLP_DESC_SHELLSECBAT"] =		"ステータスバーのバッテリーのパーセントと時・分・秒を表示します"
JAPANESE["INSTALLP_DESC_PNGSHOT"] =		"pngshotはスクリーンショットを撮影する為のプラグインです(拡張子: .png)"
JAPANESE["INSTALLP_DESC_VFLUX"] =		"PS Vitaのスクリーンフィルタープラグイン"
JAPANESE["INSTALLP_DESC_RESKYPE"] =		"FW3.65以上でSkypeアプリを有効にする為のシンプルなプラグイン"
JAPANESE["INSTALLP_DESC_AUTOBOOT"] =		"このプラグインは、単に自動起動の様なEnsoスタートアップ直後にPSPでアプリケーションを自動的に行う為に使用されます"

--ALL
JAPANESE["INSTALLP_DESC_VSHMENU"] =		"PS VitaゲームとHomebrewsのVSHメニューを表示するtaiHENプラグイン"
JAPANESE["INSTALLP_DESC_VITAGRAFIX"] =		"PS Vitaゲームの解像度とFPS上限を変更可能なプラグイン"
JAPANESE["INSTALLP_DESC_OVERCLOCK"] =		"taiHenの為のシンプルなオーバークロックプラグイン"
JAPANESE["INSTALLP_DESC_FRAMECOUNTER"] =	"FPSカウンタとして動作する小さなプラグインです。画面の左上にFPSカウンターが表示されます"
JAPANESE["INSTALLP_DESC_VGI"] =			"PS Vitaゲームに関する有益な情報を表示するシンプルなtaiHENのプラグイン"
JAPANESE["INSTALLP_DESC_FUCKPSSE"] =		"PSMゲームを複号化するプラグイン"
JAPANESE["INSTALLP_DESC_PSMPATCH"] =		"PSMゲームを修正することを可能にし、またPSMの自作アプリをロードするのに使用する事が出来ます"
JAPANESE["INSTALLP_DESC_ITLSENSO"] =		"Enso対応デバイスにTLS v1.2を追加します(アプリケーションのvpkが必要です)"
JAPANESE["INSTALLP_DESC_TROPHAX"] =		"PS VITA用全てのトロフィーロックの解除"
JAPANESE["INSTALLP_DESC_TURBOPAD"] =		"このプラグインを使うと、どのボタンでも連射(速射)を有効に事が出来ます"
JAPANESE["INSTALLP_DESC_RESCALER"] =		"このプラグインはPS VITA用のオリジナルのスケーラを新規の物に置き換え、シェーダを使用したフィルタリングで、ネイティブではない解像度で実行されているゲームでもグラフィックの向上を実現出来ます"
JAPANESE["INSTALLP_DESC_INFINITENET"] =		"ゲームがネット機能を無効にするのを防ぐtaiHEN向けのプラグイン"
JAPANESE["INSTALLP_DESC_FREEPSM"] =			        "PSMランタイムでPSM InAppPurchasesのデバッグ機能を有効にします"

--*NPXS10013
JAPANESE["INSTALLP_DESC_PS4LINK"] =		"好みのリモートプレイボタン設定を強制する事を可能にするtaiHEN向けのプラグイン"